version: '3.1'

services:

  verdaccio:
    image: verdaccio/verdaccio:5
    container_name: verdaccio
    restart: always
    environment:
      - VERDACCIO_PORT=${VERDACCIO_PORT}
      - VERDACCIO_PROTOCOL=${VERDACCIO_PROTOCOL}
      - VERDACCIO_USER_UID=${VERDACCIO_USER_UID}
    ports:
      - 4873:4873
    volumes:
      - ./volumes/verdaccio/conf:/verdaccio/conf
      - ./volumes/verdaccio/storage:/verdaccio/storage
      - ./volumes/verdaccio/plugins:/verdaccio/plugins
      - ./volumes/verdaccio/logs:/verdaccio/logs

  caddy:
    image: abiosoft/caddy
    container_name: caddy
    restart: always
    environment:
      - ACME_AGREE=true
      - DOMAIN=$VERDACCIO_DOMAIN
      - EMAIL=$VERDACCIO_EMAIL
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./volumes/caddy/Caddyfile:/etc/Caddyfile:ro
      - ./volumes/caddy/caddycerts:/root/.

# volumes:
#   conf:
#     driver: local
#   storage:
#     driver: local
#   plugins:
#     driver: local
#   logs:
#     driver: local

# networks:
#   node-network:
#     driver: bridge
