version: '3.1'

services:
  verdaccio:
    image: verdaccio/verdaccio:5
    container_name: verdaccio
    build: .
    restart: always
    # networks:
    #   - node-network
    environment:
      - VERDACCIO_PORT=$VERDACCIO_PORT
      - VERDACCIO_PROTOCOL=$VERDACCIO_PROTOCOL
    ports:
      - $VERDACCIO_PORT:$VERDACCIO_PORT
    volumes:
      - ./volumes/verdaccio_conf:/verdaccio/conf
      - ./volumes/verdaccio_storage:/verdaccio/storage
      - ./volumes/verdaccio_plugins:/verdaccio/plugins
      - ./volumes/verdaccio_logs:/verdaccio/logs

  # caddy:
  #   image: abiosoft/caddy
  #   restart: always
  #   environment:
  #     - ACME_AGREE=true
  #     - DOMAIN_NPM=$VERDACCIO_DOMAIN
  #     - EMAIL=$VERDACCIO_EMAIL
  #     - VERDACCIO_PORT=$VERDACCIO_PORT
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - ./Caddyfile:/etc/Caddyfile:ro
  #     - caddycerts:/root/.

# volumes:
#   conf:
#     driver: local
#   storage:
#     driver: local
#   plugins:
#     driver: local
#   logs:
#     driver: local

# networks:
#   node-network:
#     driver: bridge
