version: '3.1'

services:
  verdaccio:
    build: .
    image: "verdaccio/verdaccio:5"
    container_name: "verdaccio"
    networks:
      - node-network
    environment:
      - VERDACCIO_PORT=$VERDACCIO_PORT
      - VERDACCIO_PROTOCOL=$VERDACCIO_PROTOCOL
    ports:
      - $VERDACCIO_PORT:$VERDACCIO_PORT
    volumes:
      - conf:/verdaccio/conf
      - storage:/verdaccio/storage
      - plugins:/verdaccio/plugins
      - logs:/verdaccio/logs
    restart: always
  volumes:
    conf:
      driver: local
    storage:
      driver: local
    plugins:
      driver: local
    logs:
      driver: local
# networks:
#   node-network:
#     driver: bridge

caddy:
    image: abiosoft/caddy
    restart: always
    environment:
      - ACME_AGREE=true
      - DOMAIN_NPM=$VERDACCIO_DOMAIN
      - EMAIL=$VERDACCIO_EMAIL
      - VERDACCIO_PORT=$VERDACCIO_PORT
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/Caddyfile:ro
      - caddycerts:/root/.caddy
