version: '3.1'

services:
  verdaccio:
    image: verdaccio/verdaccio:5
    container_name: verdaccio
    build: .
    restart: always
    environment:
      - VERDACCIO_PORT=${VERDACCIO_PORT}
      - VERDACCIO_PROTOCOL=${VERDACCIO_PROTOCOL}
      - VERDACCIO_USER_UID=${VERDACCIO_USER_UID}
    ports:
      - $VERDACCIO_PORT:${VERDACCIO_PORT}
    volumes:
      - ./verdaccio_volumes/conf:/verdaccio/conf
      - ./verdaccio_volumes/storage:/verdaccio/storage
      - ./verdaccio_volumes/plugins:/verdaccio/plugins
      - ./verdaccio_volumes/logs:/verdaccio/logs
    # networks:
    #   - node-network

  # caddy:
  #   image: abiosoft/caddy
  #   restart: always
  #   environment:
  #     - ACME_AGREE=true
  #     - DOMAIN_NPM=$VERDACCIO_DOMAIN
  #     - EMAIL=$VERDACCIO_EMAIL
  #     - VERDACCIO_PORT=$VERDACCIO_PORT
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - ./Caddyfile:/etc/Caddyfile:ro
  #     - caddycerts:/root/.

# volumes:
#   conf:
#     driver: local
#   storage:
#     driver: local
#   plugins:
#     driver: local
#   logs:
#     driver: local

# networks:
#   node-network:
#     driver: bridge
